spring:
    profile.active: dev
    datasource:
        url: jdbc:mysql://localhost/api_foro_alura
        username: root
        password: 19384652
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    error:
        include-stacktrace: never
api:
    security:
        secret: ${JWT_SECRET:6947831}